---
- hosts: controller
  remote_user: root
  tasks:
    - name: Compress directory honeypot into honeypot.tar.gz
      archive:
        path: ../python-honeypot
        dest: /tmp/honeypot.tgz
      delegate_to: localhost

    - name: Copy honeypot.tar.gz to remote server
      copy:
        src: /tmp/honeypot.tgz
        dest: /root/honeypot.tgz
        owner: root
        group: root

    - name: Extract honeypot on the remote server
      unarchive:
        src: /root/honeypot.tgz
        dest: /root/
        remote_src: yes

    - name: Create /var/log/python-honeypot dir for logs
      file:
        path: /var/log/python-honeypot
        state: directory
        mode: '0600'

    - name: Remove ssh key
      ansible.builtin.file:
        path: /root/.ssh/honeypot.key
        state: absent

    - name: Create fake SSH keys
      command: ssh-keygen -t rsa -f /root/.ssh/honeypot.key -N ""

    - name: Create fake SSL cert and key
      command: openssl req -x509 -nodes -subj '/CN=localhost'  -newkey rsa:4096 -keyout /etc/pki/tls/private/key.pem -out /etc/pki/tls/certs/cert.pem -days 365

    - name: Copy python-honeypot.service to systemd
      copy:
        src: /root/python-honeypot/python-honeypot.service
        dest: /lib/systemd/system
        remote_src: yes

    - name: Copy python-honeypot.socket to systemd
      copy:
        src: /root/python-honeypot/python-honeypot.socket
        dest: /lib/systemd/system
        remote_src: yes

    #- name: Add 8080 to firewall
    #  command: firewall-cmd --permanent --add-port=8080/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload

    - name: Enable python-honeypot.service and start the honeypot
      systemd:
        name: python-honeypot.service
        state: started
        #enabled: yes
