---
- hosts: honeypots
  remote_user: root
  tasks:
    - name: Remove honeypot.tgz from remote server
      file:
        path: /root/honeypot.tgz
        state: absent

    - name: Remove python-honeypot dir
      file:
        path: /root/python-honeypot
        state: absent

    - name: Remove /var/log/python-honeypot
      file:
        path: /var/log/python-honeypot
        state: absent

    - name: Remove ssh key
      file:
        path: /root/.ssh/honeypot.key
        state: absent

    - name: Remove ssl certs
      file:
        path: /etc/ssl/certs/cert.pem
        state: absent

    - name: Remove ssl key
      file:
        path: /etc/ssl/private/key.pem
        state: absent

    - name: Disable python-honeypot.service
      systemd:
        name: python-honeypot.service
        state: stopped
        enabled: no

    - name: Remove python-honeypot.service from systemd
      file:
        path: /lib/systemd/system/python-honeypot.service
        state: absent

    - name: Insert a line at the end of a file.
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PasswordAuthentication yes
        regexp: 'PasswordAuthentication no'
